class EBUDefaults {

    static values = {
        "creator" : [],
        "contributor" : [],
        "organization" : [],
        "title.title": {
            "name": 'title.title',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "title.titleNote": {
            "name": 'title.titleNote',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "title.descriptiveTitle": {
            "name": 'title.descriptiveTitle',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "title.descriptiveTitleNote": {
            "name": 'title.descriptiveTitleNote',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "title.discTitle": {
            "name": 'title.discTitle',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "title.discTitleNote": {
            "name": 'title.discTitleNote',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "title.note": {
            "name": 'title.note',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "description.tags": {
            "name": 'description.tags',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "description.subject": {
            "name": 'description.subject',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "description.text": {
            "name": 'description.text',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.coverage.daterecorded": {
            "name": 'dates.coverage.daterecorded',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        }, 
        "dates.issued.firstIssued": {
            "name": 'dates.issued.firstIssued',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.issued.lastIssued": {
            "name": 'dates.issued.lastIssued',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.dateDigitalised": {
            "name": 'dates.dateDigitalised',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.videoLinks": {
            "name": 'dates.videoLinks',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.publicationHistory": {
            "name": 'dates.publicationHistory',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.publicationHistory.firstPublicationDate": {
            "name": 'dates.publicationHistory.firstPublicationDate',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.publicationHistory.firstPublicationTime": {
            "name": 'dates.publicationHistory.firstPublicationTime',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.publicationHistory.firstPublicationChannel": {
            "name": 'dates.publicationHistory.firstPublicationChannel',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.publicationHistory.repeatChannel": {
            "name": 'dates.publicationHistory.repeatChannel',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.archiveData.filesize": {
            "name": 'dates.archiveData.filesize',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.archiveData.filename": {
            "name": 'dates.archiveData.filename',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.archiveData.archiveLocation": {
            "name": 'dates.archiveData.archiveLocation',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "dates.archiveData.archiveFilePath": {
            "name": 'dates.archiveData.archiveFilePath',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.genre": {
            "name": 'videoInformation.genre',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.targetgroup": {
            "name": 'videoInformation.targetgroup',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.showType.series": {
            "name": 'videoInformation.showType.series',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.showType.type": {
            "name": 'videoInformation.showType.type',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.parts": {
            "name": 'videoInformation.parts',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.version": {
            "name": 'videoInformation.version',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.language": {
            "name": 'videoInformation.language',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.relation": {
            "name": 'videoInformation.relation',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.source": {
            "name": 'videoInformation.source',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.category": {
            "name": 'videoInformation.category',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.rating.ratingValue": {
            "name": 'videoInformation.rating.ratingValue',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.rating.ratingScaleMinValue": {
            "name": 'videoInformation.rating.ratingScaleMinValue',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.rating.ratingScaleMaxValue": {
            "name": 'videoInformation.rating.ratingScaleMaxValue',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoInformation.rating.notes": {
            "name": 'videoInformation.rating.notes',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.coverage.startDate": {
            "name": 'rights.copyright.coverage.startDate',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.coverage.endDate": {
            "name": 'rights.copyright.coverage.endDate',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.coverage.locations": {
            "name": 'rights.copyright.coverage.locations',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.exploitationIssues": {
            "name": 'rights.copyright.exploitationIssues',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.disclaimer": {
            "name": 'rights.copyright.disclaimer',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.rightClearanceFlag": {
            "name": 'rights.copyright.rightClearanceFlag',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.copyright.rightId": {
            "name": 'rights.copyright.rightId',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.usageRights.coverage": {
            "name": 'rights.usageRights.coverage',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.usageRights.exploitationIssues": {
            "name": 'rights.usageRights.exploitationIssues',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        }, 
        "rights.usageRights.disclaimer": {
            "name": 'rights.usageRights.disclaimer',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.usageRights.rightClearanceFlag": {
            "name": 'rights.usageRights.rightClearanceFlag',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "rights.usageRights.rightId": {
            "name": 'rights.usageRights.rightId',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        },
        "videoformat": {
            "name": 'videoformat',
            "type": 'input',
            "value": '',
            "changedBy": '',
            "lastModified": '',
        }
    }
}


module.exports = {
    EBUDefaults,
  };  